stages:
  create-conda-env:
    cmd: >
      mamba env create -y &&
      mamba env export -n bl-turb-mod > environment.lock.yml
    deps:
      - environment.yml
    outs:
      - environment.lock.yml:
          cache: false
  extract-jhtdb-stats:
    cmd: python -c "import jhtdb; jhtdb.read_stats()"
    deps:
      - jhtdb.py
    outs:
      - data/jhtdb-transitional-bl/all-stats.h5
    desc: |
      Download statistics at various points in the flowfield. Note that this
      has already been run with make_stats(), so we don't rerun it here to
      not do this expensive step, which requires an access token for the
      JHTDB.
  compute-coeffs:
    cmd: mkdir -p results && echo "{}" > results/coeffs.json
    deps:
      - data/jhtdb-transitional-bl/all-stats.h5
    outs:
      - results/coeffs.json
  build-sim-docker:
    cmd: cd sim && make docker
    deps:
      - sim/Dockerfile
      - sim/newModel/src/ransFromDns
    outs:
      - sim/Dockerfile.digest:
          cache: false
  mesh-independence:
    matrix:
      ny: [15, 20, 30, 40, 60]
      turbulence: [k-epsilon]
    cmd: >
      cd sim && bash run-docker.sh
      python run.py --ny ${item.ny} -f --turbulence-model ${item.turbulence}
    deps:
      - sim/system/blockMeshDict.template
      - sim/run.py
      - sim/system/sample
    outs:
      - sim/cases/${item.turbulence}-ny-${item.ny}/postProcessing
  strip-notebook-outputs:
    cmd: conda run -n bl-turb-mod calkit nb clean notebook.ipynb
    deps:
      - notebook.ipynb
    outs:
      - .calkit/notebooks/cleaned/notebook.ipynb:
          cache: false
  run-notebook:
    cmd: conda run -n bl-turb-mod calkit nb execute --to=html notebook.ipynb
    deps:
      - .calkit/notebooks/cleaned/notebook.ipynb
      - sim/cases/k-epsilon-ny-15/postProcessing
      - sim/cases/k-epsilon-ny-20/postProcessing
      - sim/cases/k-epsilon-ny-30/postProcessing
      - sim/cases/k-epsilon-ny-40/postProcessing
      - sim/cases/k-epsilon-ny-60/postProcessing
    outs:
      - .calkit/notebooks/html/notebook.html
  plot-time-ave-profiles:
    cmd: mkdir -p figures && touch figures/time-ave-profiles.pdf
    deps:
      - sim/results/time-ave-profile.csv
      - data/jhtdb-transitional-bl/time-ave-profiles.h5
    outs:
      - figures/time-ave-profiles.pdf
  plot-bl-dns:
    deps:
      - data/jhtdb-transitional-bl/all-stats.h5
      - scripts/plot-bl-dns.py
    cmd: python scripts/plot-bl-dns.py
    outs:
      - figures/bl-profile-dns.pdf
  build-paper:
    cmd: latexmk -pdf paper.tex
    wdir: paper
    deps:
      - paper.tex
      - ../figures/time-ave-profiles.pdf
      - ../figures/bl-profile-dns.pdf
      - ../references.bib
    outs:
      - paper.pdf
