stages:
  create-conda-env:
    cmd: >
      mamba env update &&
      mamba env export -n bl-turb-mod > environment.lock.yml
    deps:
      - environment.yml
    outs:
      - environment.lock.yml:
          cache: false
  strip-notebook-outputs:
    cmd: conda run -n bl-turb-mod calkit nb clean notebook.ipynb
    deps:
      - notebook.ipynb
    outs:
      - .calkit/notebooks/cleaned/notebook.ipynb:
          cache: false
  run-notebook:
    cmd: conda run -n bl-turb-mod calkit nb execute --html notebook.ipynb
    deps:
      - .calkit/notebooks/cleaned/notebook.ipynb
    outs:
      - .calkit/notebooks/html/notebook.html
  extract-jhtdb-stats:
    cmd: python -c "import jhtdb; jhtdb.read_stats()"
    deps:
      - jhtdb.py
    outs:
      - data/jhtdb-transitional-bl/all-stats.h5
    desc: |
      Download statistics at various points in the flowfield. Note that this
      has already been run with make_stats(), so we don't rerun it here to
      not do this expensive step, which requires an access token for the
      JHTDB.
  compute-coeffs:
    cmd: mkdir -p results && echo "{}" > results/coeffs.json
    deps:
      - data/jhtdb-transitional-bl/all-stats.h5
    outs:
      - results/coeffs.json
  build-sim-docker:
    cmd: cd sim && make docker
    deps:
      - sim/Dockerfile
      - sim/newModel/src/ransFromDns
    outs:
      - sim/Dockerfile.digest
  create-mesh:
    cmd: cd sim && make clean-all && make mesh
    deps:
      - sim/system/blockMeshDict
      - sim/Dockerfile.digest
    outs:
      - sim/constant/polyMesh:
          cache: false
      - sim/log.blockMesh:
          cache: false
  run-rans-sim:
    cmd: >
      mkdir -p sim/results
      && touch sim/results/time-ave-profile.csv
      && cd sim
      && make clean-sim
      && make run-sim
    deps:
      - sim/system
      - sim/constant/transportProperties
      - sim/constant/turbulenceProperties
      - sim/0
      - sim/constant/polyMesh
      - results/coeffs.json
    outs:
      - sim/results/time-ave-profile.csv
      - sim/100:
          cache: false
      - sim/180:
          cache: false
      - sim/log.simpleFoam:
          cache: false
  sample-rans-sim:
    cmd: cd sim && make post-process
    deps:
      - sim/system/sample
      - sim/180
    outs:
      - sim/postProcessing
  plot-time-ave-profiles:
    cmd: mkdir -p figures && touch figures/time-ave-profiles.pdf
    deps:
      - sim/results/time-ave-profile.csv
      - data/jhtdb-transitional-bl/time-ave-profiles.h5
    outs:
      - figures/time-ave-profiles.pdf
  plot-bl-dns:
    deps:
      - data/jhtdb-transitional-bl/all-stats.h5
      - scripts/plot-bl-dns.py
    cmd: python scripts/plot-bl-dns.py
    outs:
      - figures/bl-profile-dns.pdf
  build-paper:
    cmd: latexmk -pdf paper.tex
    wdir: paper
    deps:
      - paper.tex
      - ../figures/time-ave-profiles.pdf
      - ../figures/bl-profile-dns.pdf
      - ../references.bib
    outs:
      - paper.pdf
