name: bl-turb-mod
channels:
  - conda-forge
dependencies:
  - anyio=3.6.2
  - appdirs=1.4.4
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.2
  - black=23.1.0
  - bleach=6.0.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.7.4
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.7
  - cryptography=39.0.1
  - cycler=0.11.0
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - filelock=3.9.0
  - flit-core=3.8.0
  - fonttools=4.38.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - gdown=5.2.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - h5py=3.8.0
  - hdf5=1.14.0
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.12.0
  - ipykernel=6.21.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - isoduration=20.11.0
  - isort=5.12.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg
  - jsonpointer=3.0.0
  - jsonschema=4.17.3
  - jsonschema-with-format-nongpl=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.0.3
  - jupyter_console=6.6.1
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_server=2.3.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libnghttp2=1.51.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mpc=1.3.1
  - mpfr=4.1.0
  - mpmath=1.2.1
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbclassic=0.5.2
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.3
  - numpy=1.20.3
  - openjpeg=2.5.0
  - openssl=3.3.1
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.11.0
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.0.0
  - pooch=1.6.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytz=2022.7.1
  - pyyaml=6.0.1
  - pyzmq=25.0.0
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - readline=8.1.2
  - requests=2.28.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.0
  - setuptools=67.4.0
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlitedict=2.0.0
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - sympy=1.11.1
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.9.0
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - uri-template=1.3.0
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - wurlitzer=3.0.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zstd=1.5.2
  - pip:
      - kaleido==0.2.1
      - plotly
      - pyjhtdb==20200909.0
      - scikit-learn
